#!/usr/bin/env ruby

class ClangSource
  def initialize
    @lines = { }
    @files = { }
  end
  def file fileno
    @files[fileno] or raise "no file number #{fileno}"
  end
  def file_lines file
    @lines[file] ||= File.open(file).readlines
  end
  def show_line! file, lineno, pos
    o = $stdout
    o.puts  " # #{file}:#{lineno}"
    lineno -= 1
    line = file_lines(file)[lineno]
    if line =~ /^\{/
      lineno -= 1
      line = file_lines(file)[lineno]
      o.write " # "; o.write line
      lineno += 1
      line = file_lines(file)[lineno]
    end
    o.write " # "; o.write line
    if pos && pos > 0
      o.write " #"
      o.write "-" * (pos)
      o.puts "^"
    end
    self
  end
  def run!
    until ARGF.eof?
      line = ARGF.readline
      $stdout.write line
      case line
      when / ## ([^:]+):(\d+):(\d+)/
        show_line! $1, $2.to_i, $3.to_i
      when /^\s*\.file (\d+) "([^"]+)"/
        @files[$1.to_i] = $2
      when /^\s*\.loc (\d+) (\d+) (\d+)/
        show_line! file($1.to_i), $2.to_i, $3.to_i
      end
    end
    self
  end
end
ClangSource.new.run!
