#!/usr/bin/env ruby

class ClangSource
  def initialize
    @lines = { }
  end
  def file_lines file
    @lines[file] ||= File.open(file).readlines
  end
  def run!
    until ARGF.eof?
      line = ARGF.readline
      $stdout.write line
      case line
      when / ## ([^:]+):(\d+):(\d+)/
        $stdout.write " # "
        $stdout.write file_lines($1)[$2.to_i - 1]
        $stdout.write " #"
        $stdout.write "-" * ($3.to_i)
        $stdout.puts "^"
      end
    end
    self
  end
end
ClangSource.new.run!
