CG(jit_type_t, jit_type_void)
CG(jit_type_t, jit_type_sbyte)
CG(jit_type_t, jit_type_ubyte)
CG(jit_type_t, jit_type_short)
CG(jit_type_t, jit_type_ushort)
CG(jit_type_t, jit_type_int)
CG(jit_type_t, jit_type_uint)
CG(jit_type_t, jit_type_nint)
CG(jit_type_t, jit_type_nuint)
CG(jit_type_t, jit_type_long)
CG(jit_type_t, jit_type_ulong)
CG(jit_type_t, jit_type_float32)
CG(jit_type_t, jit_type_float64)
CG(jit_type_t, jit_type_nfloat)
CG(jit_type_t, jit_type_void_ptr)

CG(jit_type_t, jit_type_sys_bool)
CG(jit_type_t, jit_type_sys_char)
CG(jit_type_t, jit_type_sys_schar)
CG(jit_type_t, jit_type_sys_uchar)
CG(jit_type_t, jit_type_sys_short)
CG(jit_type_t, jit_type_sys_ushort)
CG(jit_type_t, jit_type_sys_int)
CG(jit_type_t, jit_type_sys_uint)
CG(jit_type_t, jit_type_sys_long)
CG(jit_type_t, jit_type_sys_ulong)
CG(jit_type_t, jit_type_sys_longlong)
CG(jit_type_t, jit_type_sys_ulonglong)
CG(jit_type_t, jit_type_sys_float)
CG(jit_type_t, jit_type_sys_double)
CG(jit_type_t, jit_type_sys_long_double)

CG(jit_abi_t, jit_abi_cdecl)
CG(jit_abi_t, jit_abi_vararg)
CG(jit_abi_t, jit_abi_stdcall)
CG(jit_abi_t, jit_abi_fastcall)

CG(int, JIT_CALL_NOTHROW)
CG(int, JIT_CALL_NORETURN)
CG(int, JIT_CALL_TAIL)

