
(quote a)
(car '(a b))
(cdr '(a b))
(cons 'a 'b)
((lambda (a b)
  (car a)
  (cdr b)
  (cons a b))
  '(1 2) '(3 4))
(if #t 'true 'false)
(if #f 'true 'false)
(if #t 'true)
(if #f 'true)

(define a (lambda () 
            (display "a")(newline)
            (b)))
(define b (lambda ()
            (display "b")(newline)
            (a)))
(a)
