(define-constant %unspec %unspec)
(define-constant %NULL %NULL)
(define-constant %word-size %word-size)
(define-constant %eos %eos)

(define-constant <type> <type>)
(define-constant <boolean> <boolean>)
(define-constant <primitive> <primitive>)
(define-constant <closure> <closure>)
(define-constant <port> <port>)
(define-constant <null> <null>)
(define-constant <fixnum> <fixnum>)
(define-constant <character> <character>)
(define-constant <symbol> <symbol>)
(define-constant <string> <string>)
(define-constant <pair> <pair>)
(define-constant <environment> <environment>)
(define-constant <vector> <vector>)
