(define *command-line* (cons #f '()))
(define (command-line) *command-line*) ;; r6rs
(define *program-directory* #f)
(define (tl_main argc argv)
  (define (fill-args tail i)
    (if (< i argc)
      (begin
        (set-cdr! tail (cons (tl_s+ (tl_get argv i)) '()))
        (fill-args (cdr tail) (+ i 1)))))
  (set! argc (tl_i argc))
  (fill-args *command-line* 0)
  (set! *command-line* (cdr *command-line*))
  (set! *program-directory* (path-directory (car *command-line*)))
  (display "TL: Ready!")(newline)
  (let ((in tl_stdin) (output tl_stdout) (prompt '()))
    (repl %env in output prompt)))
