
(define (repl env in out prompt)
  (define (read-eval-print)
    (%with-error-handler 
      (lambda ()
        (let ((expr #f) (result #f))
          (if prompt (display "> " prompt))
          (set! expr (read in))
          (if (eof-object? expr)
            (cons #f result)
            (begin
              (set! result (eval expr env))
              (if (and out (not (eq? %unspec result)))
                (begin (write result out)(newline out)))
              (cons #t result)))))))
  (define (read-eval-print-loop last-result)
    (let ((result (read-eval-print)))
      (if (car result)
        (read-eval-print-loop (cdr result))
        last-result)))
  (if (null? in)        (set! in tl_stdin))
  (if (null? out)       (set! out tl_stdout))
  (if (and (null? prompt)
	   (tl_b (isatty (fileno (->FILE* in)))))
    (set! prompt out))
  (if (null? prompt) (set! prompt #f))
  (read-eval-print-loop #f))

