F0(bool,InitializeNativeTarget)
F0(LLVMContextR,getGlobalContext)
D(PassManager)
C0(PassManager)
C2(Module,charP,name,LLVMContextR,cntx)
IM1(void,PassManager,run,ModuleR,mod)
C1(EngineBuilder,ModuleP,mod)
CM2(IntegerTypeP,IntegerType,get,LLVMContextR,cntx,int,size)
